@startuml
scale 1
class Edificio
{
    - {static} Habitacion habitacion
    + {static} areaConMayorSuciedadEnHabitacion()
    + {static} main()
    + {static} esPosibleMoverseA(int x, int y)
}
class Habitacion
{
    - Celda[][] suelo
    - int ancho
    - int largo
    - Aspiradora aspiradora
    - Gato gato
    + constructor(int ancho, int largo)
    + limpiarHabitacion()
    + mostrarHabitacion()
    + suciedadTotal()
    + areaConMayorSuciedad()
    + suciedadRestante()
    + esTraspasable(int x, int y)
}

class Celda{
    - int posX
    - int posY
    - Suciedad suciedad
    + esTraspasable(int x, int y)
    + dibujar()
}

interface Entidad {
    - int[][] coordenadasDeMovimiento
    + mover(int posX, int posY)
    + proximoMovimiento()
}
class Aspiradora implements Entidad{
    + {static} String representacion
    - Bateria bateria
    - Bolsa bolsa
    - int pasos
    + constructor()
    + limpiar()
    + bolsaLlena()
    + cargaBateria()
    + cargarBateria()
    + vaciarBolsa()
    + areaConMayorSuciedad()
}

class Gato implements Entidad{
    + {static} String representacion
    - bool estado
    - int impaciencia
    + constructor()
    + cambioEstado()
    + ensuciar()
}
class Mueble{
    - Map<String, String> tipoDeMueble
    + constructor()
    + getTipoDeMueble()
}

class Suciedad {
    - String[] representacionesDeSuciedad
    - int nivelDeSuciedad
    + constructor()
    + getNivelDeSuciedad()
    + aumentarSuciedad()
    + reducirSuciedad()
}

class Batería{
    - int carga
    - int cantidad
    + constructor()
    + cargar()
    + descargar()
}

class Bolsa{
    - int capacidad
    - int cantidad
    + constructor()
    + llenar()
    + vaciar()
}


Edificio *--> Habitacion

Habitacion *-r-> Celda : contiene

Celda ..> Aspiradora
Celda ..> Gato
Celda ..> Mueble

Aspiradora o--> Suciedad : elimina
Aspiradora *-d-> Bolsa : tiene
Aspiradora *-d-> Batería : tiene
Aspiradora -u-> Edificio


Gato o..> Suciedad : produce

@enduml
