@startuml
[*] --> Funcional
Funcional --> Sin_Energia : Se acaba la energía
Funcional --> Bolsa_Llena : La bolsa de basura se llena
Sin_Energia --> Funcional : Aspiradora cargada
Bolsa_Llena --> Funcional : Aspiradora es vaciada de la basura
@enduml