@startuml
[*] --> Funcional
Funcional --> No_Funcional
Funcional <-- No_Funcional

state Funcional {
    [*] --> Bateria_Con_Carga
    [*] --> Contenedor_No_Lleno
    [*] --> Mapa_Con_Suciedad
}

state No_Funcional {
    [*] --> Sin_Bateria
    [*] --> Contenedor_Lleno
    [*] --> Mapa_Limpio
}

Mapa_Limpio --> [*]

@enduml