@startuml
scale 2
class Edificio {
    - Habitacion habitacion
    + limpiarEdificio(Habitacion habitacion, Aspiradora aspiradora)
    + main()
}

class Habitacion{
    - Celda[][] suelo
    - Aspiradora aspiradora
    - Gato gato
    - Mueble[] muebles
    - Silla[] sillas
    + {static} mostrarHabitacion(Celda[][] suelo)
    + actualizarHabitacion(Celda[][] suelo)
}
class Celda {
    - int posX
    - int posY
    - String representacion
    + getPosX()
    + setPosX(int posX)
    + getPosY()
    + setPosY(int posY)
    + getRepresentacion()
    + setRepresentacion(String representacion)
}
class Aspiradora
class Suciedad
class Batería
class Gato
class Bolsa
class Objeto
class Mueble
class Silla

Edificio *--> Habitacion
Habitacion *--> Celda : contiene
Habitacion *-r-> Objeto
Habitacion *-l-> Aspiradora 
Habitacion *--> Gato 

Celda o..> Suciedad

Aspiradora o--> Suciedad : elimina
Aspiradora *-r-> Bolsa : tiene
Aspiradora *-l-> Batería : tiene
Aspiradora ..> Celda

Gato o..> Suciedad : produce

Objeto <|-- Mueble
Objeto <|-- Silla

@enduml