@startuml
class Mapa
class Aspiradora
class Suciedad
class Batería
class Gato
class Bolsa

Aspiradora --> Suciedad : elimina
Suciedad ..> Mapa: del
Aspiradora --> Bolsa : tiene
Aspiradora --> Batería : tiene
Gato ..> Suciedad : produce

@enduml
