@startuml
class Habitacion
class Aspiradora
class Suciedad
class Batería
class Gato
class Bolsa
class Objeto
class Celda
class Mueble
class Silla

Habitacion *--> Celda : contiene
Habitacion *--> Aspiradora
Habitacion *--> Gato
Celda o..> Suciedad
Celda o--> Objeto

Aspiradora o--> Suciedad : elimina
Aspiradora *--> Bolsa : tiene
Aspiradora *--> Batería : tiene

Gato o..> Suciedad : produce

Objeto <|-- Mueble
Objeto <|-- Silla

@enduml